schema: http://localhost:8080/graphql
documents: ./src/**/*.graphql
generates:
  ./src/app/generated/graphql.ts:
    config:
      noNamespaces: true
      resolvers: false
      enumsAsTypes: true
      avoidOptionals: true
      immutableTypes: false
      skipTypename: true
      scalars:
        Long: number
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
require: []
