# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
       
    - name: Build with Maven
      working-directory: championship-manager-api
      run: mvn -B package --file pom.xml
      
    - name: Upload jar
      uses: actions/upload-artifact@v2.2.1
      with:
        # Artifact name
        name: championship-manager.jar
        # A file, directory or wildcard pattern that describes what to upload
        path: championship-manager-api/championship-manager-app/target/championship-manager*.jar
        if-no-files-found: error

  release:
    needs: build-api
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2
          
      - name: build ui for electron
        working-directory: championship-manager-ui
        run: npm run buildElectron
      
      - name: download api jar in championship-manager-desktop
        uses: actions/download-artifact@v2.0.6
        with:
          # Artifact name
          name: championship-manager.jar
          # Destination path
          path: championship-manager-desktop/
  
      - name: build desktop app
        working-directory: championship-manager-desktop
        run: npm run electron:mac                
  
